---
form: anc_counselling_treatment
fields:
  - "danger_signs"
  - "bp_systolic_repeat"
  - "bp_diastolic_repeat"
  - "severe_hypertension"
  - "symp_sev_preeclampsia"
  - "hypertension"
  - "preeclampsia"
  - "severe_preeclampsia"
  - "body_temp_repeat"
  - "pulse_rate_repeat"
  - "respiratory_exam"
  - "respiratory_exam_abnormal"
  - "respiratory_exam_abnormal_other"
  - "oximetry"
  - "cardiac_exam"
  - "cardiac_exam_abnormal"
  - "cardiac_exam_abnormal_other"
  - "breast_exam"
  - "abdominal_exam"
  - "abdominal_exam_abnormal"
  - "abdominal_exam_abnormal_other"
  - "pelvic_exam"
  - "pelvic_exam_abnormal"
  - "pelvic_exam_abnormal_other"
  - "fetal_heartbeat"
  - "fetal_heart_rate_repeat"
  - "caffeine_intake"
  - "behaviour_persist"
  - "tobacco_user"
  - "shs_exposure"
  - "condom_use"
  - "alcohol_substance_use"
  - "phys_symptoms"
  - "phys_symptoms_persist"
  - "other_sym_lbpp"
  - "other_sym_vvo"
  - "pop_undernourish"
  - "bmi"
  - "weight_cat"
  - "exp_weight_gain"
  - "weight_gain"
  - "tot_weight_gain"
  - "health_conditions"
  - "hiv_positive"
  - "hepb_positive"
  - "syphilis_positive"
  - "pop_syphilis"
  - "asb_positive"
  - "gdm"
  - "gdm_risk"
  - "dm_in_preg"
  - "anaemic"
  - "tb_screening_result"
  - "preeclampsia_risk"
  - "pop_low_calcium"
  - "hiv_risk"
  - "pop_hiv_incidence"
  - "partner_hiv_status"
  - "hiv_test_partner_status"
  - "age"
  - "fetal_presentation"
  - "c_sections"
  - "no_of_fetuses"
  - "rh_factor"
  - "urine_culture"
  - "site_ipv_assess"
  - "pop_anaemia_40"
  - "pop_anaemia_20"
  - "ifa_effects"
  - "pop_helminth"
  - "pop_malaria"
  - "medications"
  - "tt_immun_status"
  - "flu_immun_status"
  - "pop_vita"
---
form: anc_profile
fields:
  - "site_anc_hiv"
  - "site_ultrasound"
  - "contact_no"
  - "no_of_fetuses"
  - "bmi"
  - "urine_glucose"
  - "gdm"
  - "dm_in_preg"
  - "hiv_test_result"
  - "pop_hepb"
  - "pop_hepb_screening"
---
form: anc_physical_exam
fields:
  - "prev_preg_comps"
  - "health_conditions"
  - "urine_glucose"
  - "contact_no"
  - "current_weight"
  - "pop_undernourish"
  - "dm_in_preg"
  - "hb_results"
  - "gest_age"
  - "last_contact_date"