name: Android CI with Gradle

on:
  push:
    branches: [ master, develop]
  pull_request:
    branches: [ master, develop]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out repo
      uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Print Java version
      run: java -version
    - name: Install NDK
      run: echo "y" | sudo ${ANDROID_HOME}/tools/bin/sdkmanager --install "ndk;21.0.6113669" --sdk_root=${ANDROID_SDK_ROOT}   
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Run unit tests with Gradle
      run: ./gradlew opensrp-anc:clean opensrp-anc:jacocoTestReport --stacktrace -Dorg.gradle.jvmargs="-Xmx2048m -XX:+HeapDumpOnOutOfMemoryError"
    - name: Generate Javadoc with Gradle
      run: ./gradlew javadoc
    - name: Upload coverage to Coveralls with Gradle
      run: ./gradlew opensrp-anc:coveralls --stacktrace
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_TOKEN }}

